In [14]:
%matplotlib inline
from process_flux_data import *
path = '../research/star_systems/TOI-4504/lightkurve/'

In [15]:
df = csv2df(path+"1/1_QLP_1800.csv")
df

             time      flux  flux_err
0     1325.322718  1.001950  0.001267
1     1325.343551  1.000378  0.001267
2     1325.364384  0.998227  0.001267
3     1325.385217  0.998789  0.001267
4     1325.406050  0.997462  0.001267
...           ...       ...       ...
1243  1353.072426  1.001339  0.001267
1244  1353.093259  1.003176  0.001267
1245  1353.114092  1.002607  0.001267
1246  1353.134926  1.000385  0.001267
1247  1353.155759  1.002126  0.001267

[1248 rows x 3 columns]

In [18]:
df = extract_from_df(df, 1326, 1327)
# df = tess_time_2_bjd(df)
df

           time      flux  flux_err
33  1326.010209  1.002040  0.001267
34  1326.031042  1.001748  0.001267
35  1326.051875  0.999953  0.001267
36  1326.072708  1.001588  0.001267
37  1326.093541  1.001782  0.001267
38  1326.114374  0.999994  0.001267
39  1326.135207  0.999981  0.001267
40  1326.156040  0.999264  0.001267
41  1326.176873  1.000995  0.001267
42  1326.197706  1.000406  0.001267
43  1326.218539  1.002561  0.001267
44  1326.239372  1.001847  0.001267
45  1326.260206  1.000346  0.001267
46  1326.281039  1.001113  0.001267
47  1326.301872  1.000409  0.001267
48  1326.322705  1.000769  0.001267
49  1326.343538  1.000021  0.001267
50  1326.364371  1.000084  0.001267
51  1326.385204  1.000143  0.001267
52  1326.406037  1.001616  0.001267
53  1326.426870  0.999786  0.001267
54  1326.447703  1.000625  0.001267
55  1326.468536  0.997616  0.001267
56  1326.489369  1.001291  0.001267
57  1326.510202  0.999967  0.001267
58  1326.531036  1.002394  0.001267
59  1326.551869  0.998528  0.001267
60  1326.572702  1.000504  0.001267
61  1326.593535  0.999845  0.001267
62  1326.614368  1.001511  0.001267
63  1326.635201  1.000074  0.001267
64  1326.656034  0.998925  0.001267
65  1326.676867  1.001736  0.001267
66  1326.697700  1.000781  0.001267
67  1326.718533  0.998428  0.001267
68  1326.739366  0.999438  0.001267
69  1326.760199  1.001072  0.001267
70  1326.781033  1.000641  0.001267
71  1326.801866  1.000038  0.001267
72  1326.822699  0.998503  0.001267
73  1326.843532  1.002155  0.001267
74  1326.864365  1.001329  0.001267
75  1326.885198  1.000382  0.001267
76  1326.906031  1.001612  0.001267
77  1326.926864  0.999135  0.001267
78  1326.947697  0.999621  0.001267
79  1326.968530  1.000222  0.001267
80  1326.989363  1.001737  0.001267

In [19]:
df = tess_time_2_bjd(df)
df

NameError: name 'tess_time_2_bjd' is not defined